# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f9210e24bf4c39ec0ffa91f61f0379c6111cae754c1e0770702b3bf3873cb0ff5184846995e267e156d7d47f82c0d57f99dddfc6606ecc9e1d56f08539edbf5

test:
  secret_key_base: 824b2605c25b2e1cb3bb5defdaf5dc95de9b6af0f8b343a6f3fb72dcde21083a3691c3f6923a0f1f28a8e2d2ccedef606b2f07b7d4d62729fe2c206180429f6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
